# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:690v+NGzjJNLbBm+XtePnH1jvu/SPSwzajmkI3IGUkKrXw/5izEXsxsUzpUW9dZKHJdk2ku2Y+B+GhIEuQzziBwwdN8NPk4/OMooyxw1A2AWCjdxbKU3XX8U/wokbUPK0GZkrGxAaBeHQV5sJZR+Pq87hPcGhBYrZXxK0tZDdVx84iDZDV5yqxCiXyLYR28u1EeIu2+eJSyGCEm3rHTB7Pv1fgrEtqbk43v41DfXGW3r/ns2Uw==,iv:KcBZmnpSqLrK2QXdHgNb2JpV+GzMIdRsK6QfjW28rQg=,tag:iizgmZ3UwxSnNvdQlCqazg==,type:str]
sops:
  age:
    - recipient: age1x6yer33cw0zm82dn4nswcykcc4f3lfud4smywazyxsc9pwx5xpuqv3w44u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZzk2QkRyTkFtYjNUWTJ1
        bVRsZXpaTGZsVHNCTTIrdStIVStTSThrMnlRCkZhOExBdG83NWE3TzIxYzVwTnc0
        aURaNzYvWGtMckFnd0xNT0o1U0ZBSVUKLS0tIG8yVFFUSEtFM3VZYUJkbHYyQ1g5
        cjBrMU5YY21BNURHbmsxWnlGUXFBNEkKr8e9h84CLDwrCskIKqEjyZV/CWkwWiaL
        mMr46LvwlqWQ1Xzeopad3/KbNByMcQHDpW4ntvCt/KCwXtny6nqsRg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-18T14:12:56Z"
  mac: ENC[AES256_GCM,data:Q76XPSZe7L2havwjdUMDPEcgTXawbjYLqJ7q2T741WjQWv+ghT1GQpGZaG2Zbgs+R3rhVyZH0oul/EnMA5oe1TmFZP2PD3lMzL/aWWcLaF8+LAPXk2A3P/zC4bkTjR9EPy1CDAqTBx3CnHYhqYMI6Zfs2KwZHvvvKqIBCdshfOo=,iv:dwjBzvKmPyeAMTwkgtT+c2q28SPAweooZTotCqezNqQ=,tag:/uycgPZr2Nx6Goa7heBGpw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
