---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1x6yer33cw0zm82dn4nswcykcc4f3lfud4smywazyxsc9pwx5xpuqv3w44u"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1x6yer33cw0zm82dn4nswcykcc4f3lfud4smywazyxsc9pwx5xpuqv3w44u"
stores:
  yaml:
    indent: 2
