# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:AWFDi9TxWeQlynp73z5NkdCWgM9vbE6pgEepoudtmxg=,iv:Th4hOAXtcZg07DlYonfqd78+X7aHtp4a8h1BlTEfNP8=,tag:u8PMXprCNDFyOG/doypsvA==,type:str]
sops:
  age:
    - recipient: age1x6yer33cw0zm82dn4nswcykcc4f3lfud4smywazyxsc9pwx5xpuqv3w44u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRT3RTa2VKL1lTL1RGSEdV
        SWZxMVh4U2VHeVY2SWpNWnFjNjZKKzlKNEg4CmtoTjVKRUxPMEdORGJSUU1LWWh0
        Qm15L1FQNy9CSkFvMFlsV2ZWRDhkcGsKLS0tIEQ1V3ZWMkJzNFpJMVc5NXdxRmpG
        YkhCL0xFTnlkOVdDa2U0cXB0ZE56TGMKRUoXrqGC1CTex1uoo8ZNrXMeQEIgba10
        PUzyXZMTMyTU+VZiVUnr80RmPQfB3KyKefAwvef2ctrIRe1SnyWEfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-18T13:19:16Z"
  mac: ENC[AES256_GCM,data:TVH3esgo9F5GMZpe+xQ+Y7slyRfN3tGePKRe98AO4+NoEirKGkymQc15fWB8nC4fn4ENnwF5EUkAF+agl5N5nFUvJYlkap/eAKN4F/UvGqpVZdMc5PZ1FRZU4x4EfTNmQJYE0lAhQ3oxSI3jPNzXjZUG30yTKmd+q57FZx0jRy8=,iv:pozedg9nH1AHNR3IhL+x1ww4FfBqaHCPaxnWDoAUkAA=,tag:x9DEgm0Hjc2QHDv1tTjtDg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
