# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:S5PSrSBBtgClaUTWwrNgoct/at6e+hsyb4yBx83MGMY=,iv:tF+Cj/LEDRLFJ8W6YBwPsYOQmBJ0urCD5+lNPrXwMpo=,tag:dMVUETQ3yV3UEbFOnEryDQ==,type:str]
sops:
  age:
    - recipient: age1x6yer33cw0zm82dn4nswcykcc4f3lfud4smywazyxsc9pwx5xpuqv3w44u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3b3BCczN6VXlJSkdGd2Q1
        RlAvWFAvNDRJVFlGWlFlV3RGdVVQS3kzbUY4CkExT3VzL3ZWUzVLdnlPSGxYUk1a
        UXU2aVYwdmRFVjhrM2lOTnJPYlI3UzAKLS0tIFM4SjE0Ulpkdmcvb0ZJcmx3VWEw
        QjVHbklsOUxQZVB2dkZFSzMra1d6Z3MKp9iPO5jeiXtGiYnydgsdR+Od4Lx8C1xW
        hpsrnLk2rRhjyaiax9PKl434NG91203m5HMIGUZHtf6H4Q7KoNRPNQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-18T14:12:56Z"
  mac: ENC[AES256_GCM,data:uKKnv2/tx2gvTcdsLA8t4IrQLc6QDa2FoeAoqRWeCdXBzwdpE7IYpi7/gENjfn0bjikXLWthz7dQpjB7bQ2um7E9rPj1ZTN+t6j6CTYqZTOuyZc/L7dSr28lxrP5nuasQWQd84dDVF3W3gUNRQnuUT/2MMcUZMLNLPP6Bft0bZs=,iv:nDTrKJCljHhkYTUSdNlSPp3hsM/7KU55n/9ATS/jCd4=,tag:6eiEWvRYzm6w8ooen/H+ug==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
