apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ulCv8HA2fEojMGro,iv:jqQxvh2ntHT438JcCS1/M+zMa6gqCqozvZqskarVofA=,tag:DZRT6aQPSR2b9Bjswl7iwA==,type:str]
sops:
  age:
    - recipient: age1x6yer33cw0zm82dn4nswcykcc4f3lfud4smywazyxsc9pwx5xpuqv3w44u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MzhCa3ZHdDROMTRpQ09q
        ekc4SmZNYTMwUDNQanZBeWI3bXc1VHlFTVhJCklEU0V3Q1pIVy81OVlDOXg5NUE3
        clMrWlJYVkFIU016Ry93SUNnMXJnUDgKLS0tIDJYbzJvSEtwZjB0cEpINU5KbnhC
        SVVQQm9IYXRGUHhMMkxvcStFS2VWZGcKzwZPQzAdcXNAZxO4a5yMEEh0roHbzF5C
        RPU/gjyaN0nhOjmvnnD/J9vNnbFY5z6cP6GvUkGSy2UgR+f0YejREw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-18T14:27:58Z"
  mac: ENC[AES256_GCM,data:1cl4ShUPBojeO1T/FGrbDdXgbAtqHIjoGDjvgvvTGgAMzcy+5hZrQU4ObjwZE7Ie2tR6Vx3vH6/NmhfCidK6d4ulcBTpbT6/qCf0Ut8j2YB77LIqolKAWxTNpN65X1nIGnFDX3QSh5lGNebmirUmBujr/+4bysKq67cCVOpatEA=,iv:whKL9HvLFzmlTkm34Hcg0AULzY+FVSD8lKfRPVdpWqk=,tag:DSlDOAgYEXFqTbBTEfJSJg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
