apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:FUO2Vyp1A6UZAwjGgFpF37T8+Rdu24YlruavxUuIoggS/EfyozcNdlLIR/bTS+dlDxh0E+Um+TenFCSZ9Y4NKWCEKid7h+E4+q0=,iv:wqu4DsEfkCf6EQ4VVZTGZw7k0OvwYUifIyUdhExVw7E=,tag:m3bwvKgFEUTdyXxME/SoLQ==,type:str]
sops:
  age:
    - recipient: age1x6yer33cw0zm82dn4nswcykcc4f3lfud4smywazyxsc9pwx5xpuqv3w44u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMd3R5TmtLcW0rRDNpdEdw
        NWVtc0x3VG1KSGVzeTh2ekRST2lIYXQ0OG5ZClRhbHdIOHhrT250VVE4VC9ET1hv
        eWlvK05TdmptdzBOR3ZLOHBxYXhKRlEKLS0tIEV6bW95ckY2bjIydmZHdXp2NHN0
        Q0NXVjd1ZTBNeEt6Nlk4YUdBbjNsUTAKIMl7zvvQ0RWlApDIAZ+Sz4vKdw6b+BiN
        pAsNWnwvtLmpibCxhmMCFW4Q/c8q8tO1UKN0537a+dvg38GutDsnhg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-18T14:12:55Z"
  mac: ENC[AES256_GCM,data:vscJBd8FGNybHsTROBpesqUOZQWbjQtx4COfLY7CCQc60UDu56ikOm1QL8hQzRuLPiYJpFoTYtVp8TptHWInwRyaeb0ha4o/hm6FdnJnG23zDd3todKVSHLf4GaqqJ/mkesFD0v9Zv8E155zTqlr490A3kRLI+pANzPgtdUOMlc=,iv:+lY7XkDNN1/NBnouG330uVnEVe+THKrFXSC2WTrlmCU=,tag:yIZ58XEgtQ7rMBbA+3zJSw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
