# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:6Rl1PSes6/LGnIaEv/mmCerohQVG9AHj8p7rfeK8TALaIBsTR04qAg==,iv:X/RZumPjiGo2CeH1xvHnSnKm8qeJVHklZDl8eiRxoMY=,tag:obz+rTU5Zt7JgBzeDxeKPQ==,type:str]
sops:
  age:
    - recipient: age1x6yer33cw0zm82dn4nswcykcc4f3lfud4smywazyxsc9pwx5xpuqv3w44u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bmpZalZ2VHJOWk9UWHcx
        S2VSakZEUDR2WDFGczNKNW9FQm1SeWk2MEZvCksrTGhTVXdXbVhGSEcvb1dhR0pn
        cXM2cCtHbkw4OEZ1OXNUa1ZrRUNaazAKLS0tIFdUNitiL0JQLzRrT2JxbWdzVHFv
        emZCQnlmNDc0Z1l0MGVDc3g2Tm1TYUEKznDtURAcBZ8j8pXHhbzxaG1h07G8sv5x
        R/p8iKyz0Jd9SoVLrwWsBYPp8pI8VAtH4gRTmWxHeXommKdpI46oQA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-18T13:19:16Z"
  mac: ENC[AES256_GCM,data:ggu71WItgEAN9zQuFwhZoQNQwGchxDXYp/R2Fvi38nOddeiDNnVjwYwfPlhxyHxxIdEOs76gveYmHhMmwVf6IIgGVm7kVp7ERpZhipJagTr2fWI9rdeVysYRn8v3fk5wmqlwBFlpzePPuiPQMqiS9xCvLe0tkswERq+YGTKSxi0=,iv:edEDctFGz3fGzZ8KOq7eBLVc/rCICGqlGNZp+RnQcF0=,tag:iqmXXjBRcR4oqcm11SDbew==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
